# Generated by Django 4.2.5 on 2023-11-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
        ('usuario', '0002_alter_usuario_email'),
        ('entrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendamento',
            new_name='Entrega',
        ),
        migrations.AlterModelOptions(
            name='entrega',
            options={'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
    ]
