# Generated by Django 4.2.5 on 2023-10-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSala', models.CharField(help_text='Tipo da sala', max_length=50, verbose_name='Tipo')),
                ('local', models.CharField(help_text='Local da sala', max_length=50, verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
    ]
