# Generated by Django 4.2.5 on 2023-12-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(help_text='Numero de Telefone', max_length=100, verbose_name='Email'),
        ),
    ]
