# Generated by Django 4.2.5 on 2023-12-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCopia', models.CharField(default=0, max_length=20, verbose_name='Numero de Copia')),
                ('status', models.CharField(choices=[('E', 'Em uso'), ('L', 'Livre')], default='L', max_length=20, verbose_name='Status da Chave')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='sala.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Chave utilizada',
                'verbose_name_plural': 'Chaves utilizadas',
            },
        ),
    ]
